htobackup-*: transfer ftp requires credentials htobackup-domainroot: added 'age' feature for transfer local

diff --git a/htobackup/htobackup-domainroot b/htobackup/htobackup-domainroot
--- a/htobackup/htobackup-domainroot
+++ b/htobackup/htobackup-domainroot
@@ -2,8 +2,8 @@
 
 #Define variables, some has default values
 
+AGE=""
 DATE=$(date +%Y%m%d)
-DELETEDATE=$(date --date="7 days ago" +%Y%m%d)
 DESTDIR="/var/backups"
 DOCROOT="/var/www"
 DOMAIN=""
@@ -13,9 +13,9 @@ PASSWORD=""
 REMOTE=""
 REMOVE="false"
 USER=""
-TRANSPORT=""
+TRANSFER=""
 
-REQUIRED_ARGS=('TRANSPORT')
+REQUIRED_ARGS=('TRANSFER')
 
 #Usage
 
@@ -25,6 +25,9 @@ function help() {
   echo -e "Options marked with '*' are required!"
 
   echo -e "\r\nUsage:
+  -t, --transfer [ftp, local]\t\t\t * Transfer type
+
+  -a, --age DAYS\t\t\t\t Delete logs older than DAYS 
   -d, --docroot DIR\t\t\t\t Global directory for DocumentRoots (/var/www)
   -D, --domain DOMAINNAME\t\t\t Specific domain, default is all
   -k, --encryption-passphrase YOURPASSPHRASE\t Set passphrase for encrypted files
@@ -32,8 +35,7 @@ function help() {
   -L, --destdir DIR\t\t\t\t Directory on destination (/var/backups)
   -p, --password REMOTEPASSWORD\t\t\t Password for remote user
   -r, --remote REMOTEHOST\t\t\t IP or name from remote host
-  -R, --remove\t\t\t\t\t Remove backups from local directory
-  -t, --transfer [ftp, local]\t\t\t * Transfer type
+  -R, --remove\t\t\t Remove backups from local directory
   -u, --user REMOTEUSER\t\t\t\t Remote username
   -h, --help\t\t\t\t\t Print this help
   "
@@ -66,11 +68,21 @@ function check_required_args() {
 
   done
 
+  if [[ $TRANSFER == 'ftp' ]] && [[ -z $USER || -z $PASSWORD || -z $REMOTE ]]
+  then
+
+    echo -e "$0: ERROR: Transfer via 'ftp' not possible without username, password and host\r\n"
+    exit 1
+
+  fi
+
 }
 
 #Main function
 
 function backup_domainroot() {
+
+  DELETEDATE=$(date --date="${AGE} days ago" +%Y%m%d)
 
   if [ -z $ENCRYPTKEY ]
     then
@@ -115,29 +127,50 @@ function backup_domainroot() {
 
 function copy_backup() {
 
-if [ $TRANSPORT == "ftp" ]
-    then
+if [ $TRANSFER == "ftp" ]
+then
 
-      ftp -inv $REMOTE << EOF
-      user $USER $PASSWORD
-      delete domains/$OLDFILENAME
-      put $LOCALDIR/$FILENAME domains/$FILENAME
-      bye
+  ftp -inv $REMOTE << EOF
+  user $USER $PASSWORD
+  put $LOCALDIR/$FILENAME $DESTDIR/$FILENAME
+  bye
 EOF
-    elif [ $TRANSPORT == "local" ]
-    then
-      cp $LOCALDIR/$FILENAME $DESTDIR
-    fi  
+#  if [ -n $AGE ]
+#  then
 
-    echo -e $FILENAME "\t" $ENCRYPTKEY > /root/backups/domains/$FILENAME.passwd
-    chmod 400 /root/backups/domains/$FILENAME.passwd
+#    ftp -inv $REMOTE << EOF
+#    user $USER $PASSWORD
+#!pwd
+#!find  -type f -ls
+#    bye
+#EOF
 
-    if [ $REMOVE = "true" ]
-    then
-    
-      rm $LOCALDIR/$FILENAME
+# fi
 
-    fi
+
+elif [ $TRANSFER == "local" ]
+then
+
+  cp $LOCALDIR/$FILENAME $DESTDIR
+
+  if [  -n "$AGE" ]
+  then
+
+    find $DESTDIR -type f -mtime +$AGE -delete
+
+  fi
+
+fi  
+
+if [ $REMOVE = "true" ]
+then
+  
+  rm $LOCALDIR/$FILENAME
+
+fi
+
+echo -e $FILENAME "\t" $ENCRYPTKEY > /root/backups/domains/$FILENAME.passwd
+chmod 400 /root/backups/domains/$FILENAME.passwd
 
 }
 
@@ -187,7 +220,7 @@ do
       if [[ "$#" -ge 2 && "$2" != -* ]]
       then
         
-        TRANSPORT=$2
+        TRANSFER=$2
         shift 2
 
       else
@@ -294,6 +327,20 @@ do
 
       fi
       ;;
+
+    -a|--age)
+      if [[ "$#" -ge 2 && "$2" != -* ]]
+       then
+ 
+         AGE=$2
+         shift 2
+ 
+       else
+ 
+         missing_arg $1
+ 
+       fi
+       ;;
 
   esac
 
diff --git a/htobackup/htobackup-mailbox b/htobackup/htobackup-mailbox
--- a/htobackup/htobackup-mailbox
+++ b/htobackup/htobackup-mailbox
@@ -12,10 +12,10 @@ MAILROOTDIR="/home/vmail"
 PASSWORD=""
 REMOTE=""
 REMOVE="false"
-TRANSPORT=""
+TRANSFER=""
 USER=""
 
-REQUIRED_ARGS=('TRANSPORT')
+REQUIRED_ARGS=('TRANSFER')
 
 #Usage
 
@@ -66,6 +66,14 @@ function check_required_args() {
 
   done
 
+ if [[ $TRANSFER == 'ftp' ]] && [[ -z $USER || -z $PASSWORD || -z $REMOTE ]]
+  then
+
+    echo -e "$0: ERROR: Transfer via 'ftp' not possible without username, password and host\r\n"
+    exit 1
+
+ fi
+
 }
 
 
@@ -112,7 +120,7 @@ function backup_mailroot() {
 
     fi
 
-    if [ $TRANSPORT == "ftp" ]
+    if [ $TRANSFER == "ftp" ]
     then
       ftp -inv $REMOTE << EOF
       user $USER $PASSWORD
@@ -120,7 +128,7 @@ function backup_mailroot() {
       put /$LOCALDIR/$FILENAME mailboxen/$FILENAME
       bye
 EOF
-    elif [ $TRANSPORT == "local" ]
+    elif [ $TRANSFER == "local" ]
     then
       cp $LOCALDIR/$FILENAME $DESTDIR
     fi  
@@ -185,7 +193,7 @@ do
     -t|--transfer)
       if [[ "$#" -ge 2 && "$2" != -* ]]
       then
-        TRANSPORT=$2
+        TRANSFER=$2
         shift 2
       else
         missing_arg $1
diff --git a/htobackup/htobackup-mysql b/htobackup/htobackup-mysql
--- a/htobackup/htobackup-mysql
+++ b/htobackup/htobackup-mysql
@@ -69,6 +69,15 @@ function check_required_args() {
 
   done
 
+  if [[ $TRANSFER == 'ftp' ]] && [[ -z $USER || -z $PASSWORD || -z $REMOTE ]]
+  then
+
+    echo -e "$0: ERROR: Transfer via 'ftp' not possible without username, password and host\r\n"
+    exit 1
+
+  fi 
+
+
 }
 
 #Main function
