Added docroot option to htoweb-createdomain Added error handling for external scripts to htoweb-createdomain Added error handling for htoweb-createphpini Added command line options to htoweb-createphpini Added command line options to htoweb-createvhost Added command line options to htoweb-updateprivs

diff --git a/htoweb/htoweb-createdomain b/htoweb/htoweb-createdomain
--- a/htoweb/htoweb-createdomain
+++ b/htoweb/htoweb-createdomain
@@ -1,18 +1,38 @@
 #!/bin/bash
 
+#Variables, with some default values
+
+DOCROOT="/var/www"
+
+#Usage
+
 function help() {
   
   echo -e "\r\nUsage:
-  -h, --help\t      Print this help
+  -d, --docroot\t	Global directory for DocumentRoots (/var/www)
+  -h, --help\t      	Print this help
   "  
   exit 0
 
 }
 
+#Error handling
+
 function missing_arg() {
 
   echo -e "ERROR: Missing argument for $1\r\n"
   exit 1
+
+}
+
+function external_error() {
+
+  if [ "$?" -ne 0 ]
+  then
+
+    exit 1
+
+  fi
 
 }
 
@@ -24,43 +44,44 @@ createdomain() {
   DOMAIN=${1//[-._]/}
 
   #Create User
-  useradd -s /bin/false -d /var/www/$DOMAIN/htdocs $DOMAIN
+  useradd -s /bin/false -d $DOCROOT/$DOMAIN/htdocs $DOMAIN
   adduser www-data $DOMAIN
 
   #Create folders
-  mkdir -p /var/www/$DOMAIN/htdocs/public
-  mkdir /var/www/$DOMAIN/logs
-  mkdir /var/www/$DOMAIN/conf
-  mkdir /var/www/$DOMAIN/sessions
-  mkdir /var/www/$DOMAIN/tmp
+  mkdir -p $DOCROOT/$DOMAIN/htdocs/public
+  mkdir $DOCROOT/$DOMAIN/logs
+  mkdir $DOCROOT/$DOMAIN/conf
+  mkdir $DOCROOT/$DOMAIN/sessions
+  mkdir $DOCROOT/$DOMAIN/tmp
 
   #Create VirtualHost config
-  ./htoweb-createvhost $DOMAIN $FULLDOMAIN
+  ./htoweb-createvhost $FULLDOMAIN
 
   #Create FCGID Wrapper Script
-  echo -e "#!/bin/sh" >> /var/www/$DOMAIN/conf/fcgid
-  echo -e 'export PHPRC="/var/www/$DOMAIN/conf/"' >> /var/www/$DOMAIN/conf/fcgid
-  echo -e "exec /usr/bin/php5-cgi" >> /var/www/$DOMAIN/conf/fcgid
+  echo -e "#!/bin/sh" >> $DOCROOT/$DOMAIN/conf/fcgid
+  echo -e 'export PHPRC="$DOCROOT/$DOMAIN/conf/"' >> $DOCROOT/$DOMAIN/conf/fcgid
+  echo -e "exec /usr/bin/php5-cgi" >> $DOCROOT/$DOMAIN/conf/fcgid
 
   #Create php.ini
-  ./htoweb-createphpini $DOMAIN
+  ./htoweb-createphpini -d $DOCROOT $DOMAIN 
+  external_error
 
   #Set owners to dirs/files
-  chown root:$DOMAIN /var/www/$DOMAIN
-  chown $DOMAIN:$DOMAIN /var/www/$DOMAIN/*
-  chown root:root /var/www/$DOMAIN/logs
-  chown root:$DOMAIN /var/www/$DOMAIN/conf/php.ini
-  chown $DOMAIN:$DOMAIN /var/www/$DOMAIN/conf/fcgid
+  chown root:$DOMAIN $DOCROOT/$DOMAIN
+  chown $DOMAIN:$DOMAIN $DOCROOT/$DOMAIN/*
+  chown root:root $DOCROOT/$DOMAIN/logs
+  chown root:$DOMAIN $DOCROOT/$DOMAIN/conf/php.ini
+  chown $DOMAIN:$DOMAIN $DOCROOT/$DOMAIN/conf/fcgid
   
   #Set permissions to dirs/files
-  chmod 750 /var/www/$DOMAIN
-  chmod 750 /var/www/$DOMAIN/*
-  chmod 640 /var/www/$DOMAIN/conf/php.ini
-  chmod 750 /var/www/$DOMAIN/conf/fcgid
-  chmod 750 /var/www/$DOMAIN/htdocs
+  chmod 750 $DOCROOT/$DOMAIN
+  chmod 750 $DOCROOT/$DOMAIN/*
+  chmod 640 $DOCROOT/$DOMAIN/conf/php.ini
+  chmod 750 $DOCROOT/$DOMAIN/conf/fcgid
+  chmod 750 $DOCROOT/$DOMAIN/htdocs
 
   #Run htoweb-updateprivs
-  ./htoweb-updateprivs $DOMAIN
+  ./htoweb-updateprivs -d $DOCROOT $DOMAIN
 
   #Enable VirtualHost and reload Apache
   a2ensite $DOMAIN
@@ -96,9 +117,23 @@ do
 
   case $1 in
 
+    -d|--docroot)
+      if [ "$#" -gt 2 ]
+      then
+ 
+        DOCROOT=$2
+        shift 2
+
+      else
+      
+        echo -e "$0: ERROR: Missing argument for $1\r\n"
+        exit 1
+
+      fi
+      ;;
+
     -h|--help)
       help
-      shift
       ;;
 
     *)
@@ -110,4 +145,4 @@ do
 
 done
 
-#createdomain
+createdomain $1 $DOCROOT
diff --git a/htoweb/htoweb-createphpini b/htoweb/htoweb-createphpini
--- a/htoweb/htoweb-createphpini
+++ b/htoweb/htoweb-createphpini
@@ -1,10 +1,65 @@
 #!/bin/bash
 
-cat >> /var/www/$1/conf/php.ini << EOC
+#Define variables, some have default values
 
-open_basedir = /var/www/$1/htdocs/public:/var/www/$1/tmp/
-upload_tmp_dir = /var/www/$1/tmp
-soap.wsdl_cache_dir = /var/www/$1/tmp
-session.save_path = /var/www/$1/sessions
+DOCROOT="/var/www"
 
+#Main functions
+
+function create_phpini() {
+
+cat >> $DOCROOT/$DOMAIN/conf/php.ini << EOC
+open_basedir = $DOCROOT/$DOMAIN/htdocs/public:$DOCROOT/$DOMAIN/tmp/
+upload_tmp_dir = $DOCROOT/$DOMAIN/tmp
+soap.wsdl_cache_dir = $DOCROOT/$DOMAIN/tmp
+session.save_path = $DOCROOT/$DOMAIN/sessions
 EOC
+
+}
+
+#Command line options
+
+if [ "$#" -eq 0 ]
+then
+
+  echo -e "$0: ERROR: No options given.\r\n"
+  exit 1
+
+fi
+
+while [ "$#" -gt 1 ]
+do
+
+  case $1 in
+
+    -d|--docroot)
+      if [ "$#" -gt 2 ]
+      then
+
+        DOCROOT=$2
+
+      else
+
+        echo -e "$0: ERROR: Missing argument for $1\r\n"
+        exit 1
+
+      fi
+      shift 2
+      ;;
+
+    -h|--help)
+      help
+      ;;
+
+    *)
+      echo -e "$0: ERROR: Unknown option $1\r\n"
+      exit 1
+      ;;
+
+  esac
+
+done
+
+DOMAIN=${1//[-._]/}
+
+create_phpini $DOMAIN $DOCROOT
diff --git a/htoweb/htoweb-createvhost b/htoweb/htoweb-createvhost
--- a/htoweb/htoweb-createvhost
+++ b/htoweb/htoweb-createvhost
@@ -1,17 +1,29 @@
 #!/bin/bash
 
-cat >> /etc/apache2/sites-available/$1 << EOC
+#Define variables, some have default values
+
+DOCROOT="/var/www"
+DOMAIN=""
+
+#Main function
+
+function create_vhost() {
+
+FULLDOMAIN=$1
+DOMAIN=${FULLDOMAIN//[-._]/}
+
+cat >> /etc/apache2/sites-available/$DOMAIN << EOC
 <VirtualHost *:80>
-    ServerName $2
+    ServerName $FULLDOMAIN
     ServerAdmin admins@hateo.de
 
     Include /etc/apache2/mods-available/fcgid.conf
 
-    DocumentRoot /var/www/$1/htdocs/public
-    SuexecUserGroup $1 $1
+    DocumentRoot $DOCROOT/$DOMAIN/htdocs/public
+    SuexecUserGroup $DOMAIN $DOMAIN
 
-    <Directory /var/www/$1/htdocs/public>
-        FCGIWrapper /var/www/$1/conf/fcgid .php
+    <Directory $DOCROOT/$DOMAIN/htdocs/public>
+        FCGIWrapper $DOCROOT/$DOMAIN/conf/fcgid .php
         <FilesMatch \.php$>
         	SetHandler fcgid-script
         </FilesMatch>
@@ -22,8 +34,63 @@ cat >> /etc/apache2/sites-available/$1 << EOC
     </Directory>
 
     LogLevel warn
-    ErrorLog /var/www/$1/logs/error.log
-    CustomLog /var/www/$1/logs/access.log combined
+    ErrorLog $DOCROOT/$DOMAIN/logs/error.log
+    CustomLog $DOCROOT/$DOMAIN/logs/access.log combined
 </VirtualHost>
 
 EOC
+
+exit 0
+
+}
+
+#Command line options
+
+if [ "$#" -eq "1" ]
+then
+
+  if [ "$1" = "-h" -o "$1" = "--help" ]
+  then
+    
+    help
+    
+  fi  
+
+  create_vhost $1
+
+fi
+
+while [ "$#" -gt 1 ] 
+do
+
+  case $1 in
+
+    -d|--docroot)
+      if [ "$#" -gt 2 ] 
+      then
+
+        DOCROOT=$2
+        shift 2
+
+      else
+
+        echo -e "$0: ERROR: Missing argument for $1\r\n"
+        exit 1
+
+      fi  
+      ;;  
+
+    -h|--help)
+      help
+      ;;  
+
+    *)  
+      echo -e "$0: ERROR: Unknown option $1\r\n"
+      exit 1
+      ;;  
+
+  esac
+
+done
+
+create_vhost $1 $DOCROOT
diff --git a/htoweb/htoweb-updateprivs b/htoweb/htoweb-updateprivs
--- a/htoweb/htoweb-updateprivs
+++ b/htoweb/htoweb-updateprivs
@@ -1,7 +1,78 @@
 #!/bin/bash
 
-/bin/chown $1:$1 /var/www/$1/htdocs
-/usr/bin/find /var/www/$1/htdocs -type d -exec /bin/chmod 750 {} +
-/usr/bin/find /var/www/$1/htdocs -type f -exec /bin/chmod 640 {} +
+#Define variables, some have default values
+
+DOCROOT="/var/www"
+DOMAIN=""
+
+#Main function
+
+function updateprivs() {
+
+  DOMAIN=${1//[-._]/}
+
+  chown -R $DOMAIN:$DOMAIN $DOCROOT/$DOMAIN/htdocs
+  find $DOCROOT/$DOMAIN/htdocs -type d -exec chmod 750 {} +
+  find $DOCROOT/$DOMAIN/htdocs -type f -exec chmod 640 {} +
+
+  exit 0
 
 
+}
+
+#Command line options
+
+if [ "$#" -eq "0" ]
+then
+
+  help
+
+elif [ "$#" -eq "1" ]
+then
+
+  if [ "$1" = "-h" -o "$1" = "--help" ]
+  then
+    
+    help
+    
+  fi  
+
+  updateprivs $1
+
+fi
+
+
+while [ "$#" -gt 1 ]
+do
+
+  case $1 in
+
+    -d|--docroot)
+      if [ "$#" -gt 2 ]
+      then
+
+        DOCROOT=$2
+        shift 2
+
+      else
+
+        echo -e "$0: ERROR: Missing argument for $1\r\n"
+        exit 1
+
+      fi
+      ;;
+
+    -h|--help)
+      help
+      ;;
+
+    *)
+      echo -e "$0: ERROR: Unknown option $1\r\n"
+      exit 1
+      ;;
+
+  esac
+
+done
+
+updateprivs $1 $DOCROOT
